//---------------------------------------------------------------------------
#include <vcl.h>
#pragma hdrstop
USERES("cxEditorsC11.res");
USEPACKAGE("dbrtl.bpi");
USEPACKAGE("rtl.bpi");
USEPACKAGE("vcl.bpi");
USEPACKAGE("vcldb.bpi");
USEPACKAGE("vcljpg.bpi");
USEPACKAGE("vclx.bpi");
USEPACKAGE("dxCoreC11.bpi");
USEPACKAGE("dxThemeC11.bpi");
USEPACKAGE("dxThemeC11.bpi");
USEPACKAGE("cxDataC11.bpi");
USEPACKAGE("dxGDIPlusC11.bpi");
USEPACKAGE("cxLibraryC11.bpi");
USEUNIT("cxBlobEdit.pas");
USEUNIT("cxButtonEdit.pas");
USEUNIT("cxButtons.pas");
USEUNIT("cxCalc.pas");
USEUNIT("cxCalendar.pas");
USEUNIT("cxCheckBox.pas");
USEUNIT("cxCurrencyEdit.pas");
USEUNIT("cxDBEdit.pas");
USEUNIT("cxDBEditRepository.pas");
USEUNIT("cxDBLookupEdit.pas");
USEUNIT("cxEdit.pas");
USEUNIT("cxEditConsts.pas");
USEUNIT("cxEditDataRegisteredRepositoryItems.pas");
USEUNIT("cxEditDBRegisteredRepositoryItems.pas");
USEUNIT("cxEditRegisteredRepositoryItems.pas");
USEUNIT("cxEditUtils.pas");
USEUNIT("cxHyperLinkEdit.pas");
USEUNIT("cxImage.pas");
USEUNIT("cxImageComboBox.pas");
USEUNIT("cxLookupDBGrid.pas");
USEUNIT("cxLookupEdit.pas");
USEUNIT("cxLookupGrid.pas");
USEUNIT("cxMaskEdit.pas");
USEUNIT("cxNavigator.pas");
USEUNIT("cxMemo.pas");
USEUNIT("cxMRUEdit.pas");
USEUNIT("cxRegExpr.pas");
USEUNIT("cxSpinEdit.pas");
USEUNIT("cxTimeEdit.pas");
USEUNIT("cxDropDownEdit.pas");
USEUNIT("cxEditPaintUtils.pas");
USEUNIT("cxTextEdit.pas");
USEUNIT("cxStandardMask.pas");
USEUNIT("cxEditMaskEditor.pas");
USEUNIT("cxDBLookupComboBox.pas");
USEUNIT("cxRadioGroup.pas");
USEUNIT("cxListBox.pas");
USEUNIT("cxFilterControl.pas");
USEUNIT("cxFilterControlUtils.pas");
USEUNIT("cxFilterControlStrs.pas");
USEUNIT("cxFilterControlDialog.pas");
USEUNIT("cxEditRepositoryItems.pas");
USEUNIT("cxDBNavigator.pas");
USEUNIT("cxDBFilterControl.pas");
USEUNIT("cxPropertiesConverters.pas");
USEUNIT("cxGroupBox.pas");
USEUNIT("cxInplaceContainer.pas");
USEUNIT("cxCheckListBox.pas");
USEUNIT("cxProgressBar.pas");
USEUNIT("cxLabel.pas");
USEUNIT("cxTrackBar.pas");
USEUNIT("cxFontNameComboBox.pas");
USEUNIT("cxColorComboBox.pas");
USEUNIT("cxExtEditUtils.pas");
USEUNIT("cxCheckComboBox.pas");
USEUNIT("cxTreeView.pas");
USEUNIT("cxSplitter.pas");
USEUNIT("cxDBColorComboBox.pas");
USEUNIT("cxDBProgressBar.pas");
USEUNIT("cxDBLabel.pas");
USEUNIT("cxDBTrackBar.pas");
USEUNIT("cxHint.pas");
USEUNIT("cxMCListBox.pas");
USEUNIT("cxListView.pas");
USEUNIT("cxHeader.pas");
USEUNIT("cxDBCheckListBox.pas");
USEUNIT("cxDBCheckComboBox.pas");
USEUNIT("cxExtEditConsts.pas");
USEUNIT("cxSpinButton.pas");
USEUNIT("cxDBFontNameComboBox.pas");
USEUNIT("cxShellComboBox.pas");
USEUNIT("cxShellCommon.pas");
USEUNIT("cxShellControls.pas");
USEUNIT("cxShellListView.pas");
USEUNIT("cxShellTreeView.pas");
USEUNIT("cxDBShellComboBox.pas");
USEUNIT("cxShellBrowser.pas");
USEUNIT("cxShellBrowserDialog.pas");
USEUNIT("cxShellDlgs.pas");
USEUNIT("cxExtEditRepositoryItems.pas");
USEUNIT("cxShellEditRepositoryItems.pas");
USEUNIT("cxCheckGroup.pas");
USEUNIT("cxDBCheckGroup.pas");
USEUNIT("cxRichEdit.pas");
USEUNIT("cxDBRichEdit.pas");
//---------------------------------------------------------------------------
#pragma package(smart_init)
//---------------------------------------------------------------------------
//   Package source.
//---------------------------------------------------------------------------
#pragma argsused
int WINAPI DllEntryPoint(HINSTANCE hinst, unsigned long reason, void*)
{
        return 1;
}
//---------------------------------------------------------------------------
