unit AppConsts;

interface

const
  //allocation profiler result -- database structure

  ptnINSTANCES = 'INSTANCES';
  pfnINST_ID = 'INST_ID';  // 结果集标识符id
  pfnCAPTION = 'CAPTION'; // 分析结果集的日期

  ptnALLOCATION_PROFILER_CLASSES_DATA = 'ALLOCATION_PROFILER_CLASSES_DATA';
  pfnCOL_LIVE_COUNT = 'COL_LIVE_COUNT'; // 该类泄露数量
  pfnCOL_CLASS_NAME = 'COL_CLASS_NAME'; // 类名

  ptnALLOCATION_PROFILER_CREATION_CALL_STACK = 'ALLOCATION_PROFILER_CREATION_CALL_STACK';
  pfnPARENT_ID = 'PARENT_ID'; // 用于和objects表进行关联(ID)
  pfnCOL_ROUTINERID = 'COL_ROUTINERID';


  ptnALLOCATION_PROFILER_META_CLASSES_DATA = 'ALLOCATION_PROFILER_META_CLASSES_DATA';
  pfnREC_ID = 'REC_ID'; // 该字段用于和Class_data表进行关联


  ptnALLOCATION_PROFILER_META_LINES = 'ALLOCATION_PROFILER_META_LINES';
  ptnALLOCATION_PROFILER_META_ROUTINES = 'ALLOCATION_PROFILER_META_ROUTINES';
  pfnCOL_UNIT_NAME = 'COL_UNIT_NAME';
  pfnCOL_SOURCE_LINE = 'COL_SOURCE_LINE';
  pfnCOL_ROUTINE_NAME = 'COL_ROUTINENAME';


  ptnALLOCATION_PROFILER_OBJECTS = 'ALLOCATION_PROFILER_OBJECTS';
  pfnID = 'ID'; // 用于得到调用堆栈信息
  pfnCOL_CLASSRID = 'COL_CLASSRID'; // 用于和和Meta_Class_data表进行关联(REC_ID)


  ptnALLOCATION_PROFILER_REFERENCES_FROM = 'ALLOCATION_PROFILER_REFERENCES_FROM';
  ptnALLOCATION_PROFILER_REFERENCES_TO = 'ALLOCATION_PROFILER_REFERENCES_TO';
  ptnALLOCATION_PROFILER_THREADS = 'ALLOCATION_PROFILER_THREADS';
  ptnRELATIONS = 'RELATIONS';



implementation

end.
